apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-service
  template:
    metadata:
      labels:
        app: restaurant-service
    spec:
      containers:
        - name: restaurant-service
          image: restaurant-service:latest
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
            - name: MONGO_URI
              value: "mongodb+srv://chaveen:IT22129376@foodappcluster.4l6ru.mongodb.net/RestaurantDB?retryWrites=true&w=majority&appName=FoodAppCluster"
            - name: USER_SERVICE_URL
              value: "http://user-management-service:8090/users"
            - name: JWT_SECRET
              value: "20020216"
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-service
spec:
  selector:
    app: restaurant-service
  ports:
    - port: 5001
      targetPort: 5001
