apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management-service
  template:
    metadata:
      labels:
        app: user-management-service
    spec:
      containers:
        - name: user-management-service
          image: user-management-service:latest
          ports:
            - containerPort: 8090
          env:
            - name: PORT
              value: "8090"
            - name: MONGO_URI
              value: "mongodb+srv://chaveen:IT22129376@foodappcluster.4l6ru.mongodb.net/UserDB?retryWrites=true&w=majority&appName=FoodAppCluster"
            - name: JWT_SECRET
              value: "20020216"
---
apiVersion: v1
kind: Service
metadata:
  name: user-management-service
spec:
  selector:
    app: user-management-service
  ports:
    - port: 8090
      targetPort: 8090
